spring.application.name=desafioPersistenciDados
spring.datasource.url=jdbc:postgresql://localhost/desafio_persitencia_dados
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialectHSQLDialect
spring.jpa.hibernate.ddl-auto=update
